common:
  containerRegistryURL: acrtodomicroapp01.azurecr.io
  ingressClass: nginx
  
ui:
  replicas: 2
  image:
    name: todo-ui
    tag: v4
  port: 80
  ServicePort: 80
  ingress:
    host: ui.my-app-gateway.shop

getTask:
  replicas: 2
  image:
    name: todo-add-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-todoappmicro-server.database.windows.net,1433;Database=sqldb-todomicroapp;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: get-tasks-api.my-app-gateway.shop
    ingressClass: nginx

deleteTask:
  replicas: 2
  image:
    name: todo-delete-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-todoappmicro-server.database.windows.net,1433;Database=sqldb-todomicroapp;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: delete-task-api.my-app-gateway.shop
    ingressClass: nginx

addTask:
  replicas: 2
  image:
    name: todo-add-tasks-api
    tag: v1
  port: 8000
  ServicePort: 80
  connectionString: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:sql-todoappmicro-server.database.windows.net,1433;Database=sqldb-todomicroapp;Uid=devopsadmin;Pwd=P@ssw01rd@123;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
  ingress:
    host: add-task-api.my-app-gateway.shop
    ingressClass: nginx
